<?php
return [
   'APERTURA',
    'CIERRE',
    'DEPOSITO',
    'RETIRO',
    'TRANSFERENCIA',
    'Automatico',
    'BEG ESPECIAL',
    'BEG URB PRIM.1',
    'BEG URB. SEC.',
    'BEG URB. SUPERIOR.',
    'BOL. URBANO',
    'CARGA TARJETA',
    'Fuera de Hora',
    'LIPSIA',
    'PASE DISC/C  ACOMP K',
    'PASE DISCAPACITADO ',
    'PASE ESPECIAL',
    'Reporte Z',
    'Saldo rec. validado',
    'Sin Saldo 1 (Plata)',
    'TARJ MONEDERO',
    'TARJ. JUBILADO',
    'BOLETO',
    'TARJ. JUBILADO',
    'RESID. IGUAZU',
    'BOL. URBANO',
    'TARJ. ABONO',
    'TARJ MONEDERO',
    'ESTUDIANTE KENIA',
    'ESCOLAR',
    'TARJETA PASE',
    'TARJ. DOCENTE URBA',
    'TARJ. DOCENTE INTE',
    'PASE LIBRE',
    'CANJE BEG',
    'PASE ESPECIAL',
    'CARGA TARJETA',
    'XBEG SUB PRIM',
    'XBEG SUB SEC',
    'XBEG SUB TERC/UNIV',
    'XBEG INTERURBANO',
    'XBEG URBANO',
    'PASE DISCAPACITADO',
    'PASE DISC/C ACOMPA',
    'TARJ PENSIONADO',
    'TARJETA NO DOCENT',
    'BOMBERO VOLUNTAR',
    'HOTEL INT IGUAZU',
    'Encomienda',
    'COVID-19',
    'LIPSIA',
    'ENCOMIENDA KENIA',
    'BOG',
    'BOG CON ACOMP',
    'ADMINISTRATIVO',
    'S.P.P.',
    'CULTURA',
    'T. DISCAPACITADO k',
    'T. DOCENTE INT. UNI',
    'TORNEO INFANTO',
    'TARJ. JUBILADO ETCE',
    'BEG URB PRIM.',
    'BEG URB. SEC.1',
    'BEG URB. SUPERIOR1',
    'BEG URB. UNIV.',
    'BEG SUB. SEC.1',
    'BEG SUB. PRIM.1',
    'BEG SUB. SUPERIOR.',
    'BEG SUB. UNIV.1',
    'BEG INT. PRIM',
    'BEG INT. SEC',
    'BEG INT. SUPERIOR.1',
    'BEG INT. UNIV',
    'BEG ESPECIAL',
    'PASANTES EDG',
    'PASE LIBRE ELDORAD',
    'APS ELDORADO',
    'PASANTES M',
    'BOLETO CANJE',
    'URBANO P. PIRAY',
    'LOI SUITES IGUAZU',
    'JUZGADO ELDORADO',
    'PASE ESPECIAL WAND',
    'ESCOLAR ETCE',
    'ESCOLAR INTER',
    'BOL. URBANO ELDOR',
    'PASE ESPECIAL SAN V',
    'BOL ELECTORAL',
    'EST DON GUILLERMO',
    'TRANSITO ELDORADO',
    'BENEFICIO BEG SEC',
    'BENEFICIO BEG TER/',
    'RECARGA TARJETA',
    'PASE UNIFORMADO',
    'CANJE JUBILADO',
    'ABONO EDUCATIVO',
    'BENEFICIO ESCOLAR',
    'PASE DISC TARJETA',
    'BENEFICIO BEG PRI',
    'BENEFICIO ESCOLAR',
    'CANJE EDUCATIVO',
    'ABONO JUBILADO',
    'ABONO GENERAL',
    'BOLETO URBANO',
    'BOLETO URB ESPERA',
    'ESCOLAR GRAL',
    'TARJ. MONEDERO',
    'DOCENTE',
    'TARJ. DOCENTE',
    'PASE LIBRE',
    'BOL. ESCOLAR',
    'BEG URB PRIM.1',
    'BEG URB. SEC.',
    'BEG URB. SUPERIOR.',
    'BEG URB. UNIV.1',
    'BEG SUB. SEC.',
    'BEG SUB. PRIM.',
    'BEG SUB. SUPERIOR',
    'BEG SUB. UNIV.',
    'BEG INT. PRIM.',
    'BEG INT. SEC.1',
    'BEG INT. SUPERIOR',
    'BEG INT. UNIV.1',
    'ACOMP. DISC.',
    'JUBILADO 30%',
    'BOLETO',
    'SERVICIO INTER 160',
    'TARJ. DOCENTE INTE',
    'BOLETO INTER R17',
    'PERSONAL EMPRESA',
    'BAL PIRAY GUAZU',
    'PASE UNIFORMADO',
    'PASE ESP ELDORADO',
    'PASE ESP ESPERANZA',
    'PASE ESP LIBERTAD',
    'BOLETO CANJE',
    'ENCOMIENDAS ETCE',
    'UNIFORMADO',
    'Cambio Localidad GPS',
    'Cambio status equipo',
    'Carga combustible',
    'Cbio Localidad Man',
    'Chofer entrante',
    'Chofer saliente',
    'Cierre Sesión',
    'Cobro',
    'Comando Web',
    'Datos Auxiliares',
    'Emisión reporte',
    'Entrada a Terminal',
    'Equipo Bloqueado',
    'Error de Sistema',
    'Estac Peaje Manual',
    'Estación Peaje 1',
    'Estación Peaje 2',
    'Estación Peaje 3',
    'Estación Peaje 4',
    'Estación Peaje 5',
    'Estación Peaje 6',
    'Estación Peaje 7',
    'Estación Peaje 8',
    'Estación Peaje 9',
    'Evento Micronauta',
    'Evento Validador Ext',
    'Exceso velocidad',
    'Falta Papel o Apert.',
    'Fecha y hora manual',
    'Fin actualizacion',
    'Fin De Archivo',
    'Fin exceso velocidad',
    'Fin Llamada',
    'Gastos',
    'Ida',
    'Info Hardware',
    'Info Sistema',
    'Informacion',
    'Inicio actualizacion',
    'Inicio Sesión',
    'Itinerario Urbano',
    'Llamada entrante',
    'Log Administrador',
    'Mensaje Atendido',
    'Parada',
    'Parada Urbano (no)',
    'Proximo',
    'Rechazo Comp. L 2D',
    'Reinicio',
    'Reintegro Automático',
    'Reintegro Manual',
    'Salida',
    'Salida de Terminal',
    'Servicio Entrante',
    'Servicio Saliente',
    'Tarjeta Rechazada',
    'Validador Ext no sin',
    'Venta',
    'Vuelta/Cbio Sentido'
];
